
import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Blüten",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-sora mx-4 md:mx-8 lg:mx-20 py-2 " >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
